#!/bin/bash

TOKEN="Pivotal Tracker API Token"
MESSAGE=$(git log -1 HEAD --pretty=format:%s)
AUTHOR=$(git log -1 HEAD --pretty=format:%an)
REVISION=$(git log -1 HEAD --pretty=format:%h)

curl -H "X-TrackerToken: $TOKEN" -X POST -H "Content-type: application/xml" -d "<source_commit><message>$MESSAGE</message><author>$AUTHOR</author><commit_id>$REVISION</commit_id></source_commit>" https://www.pivotaltracker.com/services/v3/source_commits
